name: Publish to Docker

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: minimicrowave/bs-ui
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Set environment name
        id: set_env_name
        run: |
          echo ::set-output name=ENV_NAME::${{startsWith(github.ref, 'refs/tags/v') && 'prod' || 'staging' }}
      -
        name: Load environment variables
        run: | 
          cat ".github/${steps.set_env_name.outputs.ENV_NAME}.env" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            type=raw, value={{tag}}-${ {steps.set_env_name.outputs.ENV_NAME }}
          labels: ${{ steps.meta.outputs.labels }}