name: Publish to Docker

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set environment name
        id: set_env_name
        run: |
          echo ::set-output name=ENV_NAME::${{startsWith(github.ref, 'refs/tags/v') && 'prod' || 'staging' }}
      - 
        name: Set release tag
        id: set_release_tag
        run: |
          echo ::set-output name=RELEASE_TAG::${{steps.set_env_name.outputs.ENV_NAME == 'prod' && '-RELEASE' || '{{sha}}-STAGING'}}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: minimicrowave/bs-ui
          tags: |
            type=raw, value={{tag}}${{steps.set_release_tag.outputs.RELEASE_TAG }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Load environment variables
        run: | 
          set -a # automatically export all variables
          source ".github/${{steps.set_env_name.outputs.ENV_NAME}}.env" 
          set +a
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}